version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
